apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lrjn7sd1f-go
  janus-idp.io/tekton: lrjn7sd1f-go
  backstage.io/kubernetes-id: lrjn7sd1f-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lrjn7sd1f-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
