apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lrjn7sd1f-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lrjn7sd1f-go 
  name: lrjn7sd1f-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lrjn7sd1f-go 
